# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.7.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          image: dhanushreebhrish/upload-file-api
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - run: docker run -d -p 9100:9000 -p 5500:5500 -v C:\Users\HP\OneDrive\Documents\Dhanushree\API-Upload-Doc\Uploads:/app/Uploads -v C:\Users\HP\OneDrive\Documents\Dhanushree\API-Upload-Doc\tokens.json:/app/tokens.json -v C:\Users\HP\OneDrive\Documents\Dhanushree\API-Upload-Doc\users.json:/app/users.json  --name testing-container dhanushreebhrish/upload-file-api:latest
